use_frameworks!

platform :ios, '12.0'

pod 'WolfPipe', :path => '../../WolfPipe/'
pod 'WolfFoundation', :path => '../../WolfFoundation/'
pod 'WolfNumerics', :path => '../../WolfNumerics/'

target 'WolfSec_Example' do
  pod 'WolfSec', :path => '../'

  target 'WolfSec_Tests' do
    inherit! :search_paths
  end
end
